### ISSUE TITLE
Naming of the type sqares

### ISSUE THREAD

**Issue by jaller94** [lsh-silpion/tictactoe-react-typescript-tutorial#1]
https://github.com/lsh-silpion/tictactoe-react-typescript-tutorial/blob/62856a901fe3f3f6e975727b721062c35ac8042d/src/App.tsx#L3

* Misspelling: sqares -> squares
* Types usually start on a capital letter to distinguish them from variables: sqares -> Squares

**Comment by lsh-silpion** [comment]
Well spotted!

**Comment by lsh-silpion** [comment]
fixed in https://github.com/lsh-silpion/tictactoe-react-typescript-tutorial/commit/75a9b0e23683ba43bd5c6e411907d1a4339e28a5
